version: '3.8'

services: 
  main:
    build: 
      dockerfile: Dockerfile
      context: ./main
    command: node server.js
    image: joaod/main_calculator
    container_name: main_calculator
    ports: 
      - ${MAIN_PORT}:${PORT}
    networks: 
      - overlay
    depends_on: 
      - division
      - multiplication
      - subtraction
      - sum

  division:
    build: 
      dockerfile: Dockerfile
      context: ./division
    command: node server.js
    image: joaod/division_calculator
    container_name: ${DIVISION_NAME}
    ports: 
      - ${DIVISION_PORT}:${PORT}
    networks: 
      - overlay

  multiplication:
    build: 
      dockerfile: Dockerfile
      context: ./multiplication
    command: node server.js
    image: joaod/multiplication_calculator
    container_name: ${MULTIPLICATION_NAME}
    ports: 
      - ${MULTIPLICATION_PORT}:${PORT}
    networks: 
      - overlay

  subtraction:
    build: 
      dockerfile: Dockerfile
      context: ./subtraction
    command: node server.js
    image: joaod/subtraction_calculator
    container_name: ${SUBTRACTION_NAME}
    ports: 
      - ${SUBTRACTION_PORT}:${PORT}
    networks: 
      - overlay

  sum:
    build: 
      dockerfile: Dockerfile
      context: ./sum
    command: node server.js
    image: joaod/sum_calculator
    container_name: ${SUM_NAME}
    ports: 
      - ${SUM_PORT}:${PORT}
    networks: 
      - overlay
      
networks: 
  overlay:
    driver: overlay